### ISSUE TITLE
Change font family

### ISSUE THREAD

**Issue by hmbrg** [PKief/latex-thesis-template#1]
Hey, thanks for the great template!

Is there any way to easily change the font though? I've tried a bunch of different solutions, but I can't seem to get it to work.

Any pointer in the right directions would be greatly appreciated.

Thanks!

**Comment by PKief** [comment]
Hi @hmbrg, in LaTeX it's not that common to change the font families just like selecting some fonts in the drop down as it works in MS Word for example. LaTeX provides a built-in font which is "[backed up by well researched usability studies](https://stackoverflow.com/a/880794/6942210)".

If you don't want to have serifes, you can paste the following in one of the settings tex files:

```tex
\renewcommand{\familydefault}{\sfdefault}
```

Got this answer from https://stackoverflow.com/a/877670/6942210.

If you research something about this template, it helps if you prefix your search with "Koma Script", because it is based on Koma Script (a collection of latex classes and packages). Just as a hint ;)

Glad to hear that you like my template! Hopefully this helps you a little bit.

**Comment by hmbrg** [comment]
Thanks for the tip, your solution worked flawlessly! 

I also found this documentation with some more examples: https://de.wikibooks.org/wiki/LaTeX-W%C3%B6rterbuch:_fontfamily
