### ISSUE TITLE
Request for Assistance with Thesis Template Modifications (latex-thesis-template)

### ISSUE THREAD

**Issue by EngMuhammadSalem** [PKief/latex-thesis-template#2]
Hi PKief,

First, I would like to thank you for sharing your thesis template on GitHub. I have used it for my project and found it extremely helpful. However, I need some assistance with a few modifications:

1. I need to remove all the blank pages.
2. Please remove all the details in the headers.
3. I need the preliminary section to be numbered with Roman numerals, while the main part, appendix, and bibliography should use standard numbering, with the style matching the attached images.

I appreciate your time and support, and I look forward to your response.

Best regards,  
[Muhammad Salem]

![photo_1_2024-08-16_16-02-28](https://github.com/user-attachments/assets/70503850-b765-48b5-a74f-d51822578a98)
![photo_2_2024-08-16_16-02-28](https://github.com/user-attachments/assets/9134df16-0700-4536-999d-40641622d04d)

**Comment by PKief** [comment]
Hi Muhammad,

1.) Replace the `twoside` with `oneside` to remove the blank pages: https://github.com/PKief/latex-thesis-template/blob/3591634fb2bcfc84ce7a9fab35f5eb86b1cf0cc8/thesis.tex#L4

If you want to print out your thesis on a duplex printer (paper is printed on both sides), you've to have these blank pages, because the blank page will be the back side of a paper.

2.) Change the `pagestyle` command to `plain`:

https://github.com/PKief/latex-thesis-template/blob/3591634fb2bcfc84ce7a9fab35f5eb86b1cf0cc8/settings/layout.tex#L6

```
\pagestyle{plain} 
```

3.) To change the format of the numbering of the appendix you have to remove these lines. Then it will continue with the numbers of the main section. 

https://github.com/PKief/latex-thesis-template/blob/3591634fb2bcfc84ce7a9fab35f5eb86b1cf0cc8/thesis.tex#L109-L110

Regarding that line for the footer, I can't help you out with a quick solution. Probably you have to take a look into the [fancyhdr package](https://ctan.org/pkg/fancyhdr?lang=en).

**Comment by EngMuhammadSalem** [comment]
Dear Philipp Kief,

Thank you very much for your valuable assistance and prompt response. Your
information was very helpful, and I appreciate your time and effort.

I would like to know how I can access additional details related to this
topic so that I can fully learn it. If you have any resources or guidance
that could assist me, I would be grateful if you could share them with me.
Additionally, if I have any further questions or need additional help in
the future, would it be acceptable to reach out to you again?

Thank you once again for your support.

Best regards,

Mohamed Salem

**Comment by PKief** [comment]
You're welcome. Basically all information regarding the Latex configs of this project can be found in the official [koma script documentation](https://ctan.net/macros/latex/contrib/koma-script/doc/scrguide-en.pdf). If you've questions which are more specific to your current work, I'd highly recommend that you're using a search engine or [ChatGPT](https://chatgpt.com/) to get valuable information or even the answers in many of the Latex communities helped me to get answers to my questions. I don't have time to give you detailed support. Best regards, Philipp

**Comment by EngMuhammadSalem** [comment]
Hello PKief,

Sorry for disturbing you, and I know your right that your time is valuable,
but I need help after I was unable to find a solution to it, which is: How
can I write a chapter or section in Arabic language?

Thanks for any help

في الجمعة، ١٦ آب، ٢٠٢٤ ٦:٤٦ م Philipp Kief ***@***.***> كتب:
